name = "admin-auth-dev"
type = "javascript"
zone_id = "ZONE_ID"
account_id = "ACCOUNT_ID"
workers_dev = true
compatibility_date = "AAAA-MM-DD"
[vars]
ENVIRONMENT = "dev"

[env.development]
name = "admin-auth-development"
workers_dev = false
route = "dev-api.codelearn.space/login/*"
[env.development.vars]
ENVIRONMENT = "dev"


[env.staging]
name = "admin-auth-staging"
workers_dev = false
route = "staging-api.codelearn.space/login/*"
[env.staging.vars]
ENVIRONMENT = "staging"


[env.production]
name = "admin-auth"
workers_dev = false
route = "api.codelearn.space/login/*"
[env.production.vars]
ENVIRONMENT = "production"

[build]
command = "npm install && npm run build"
[build.upload]
format = "service-worker"

[dev]
ip = "127.0.0.1"
port = 3000
local_protocol="http"
upstream_protocol="https"

# [secrets.env]
# key